# Generated by Django 3.1.7 on 2021-03-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_centers', '0002_auto_20210327_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='availableServices',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='baseVisitingCharges',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='centerName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='closingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='locationCity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='locationPinCode',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='locationState',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='numberOfMechs',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='openingTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
