# Generated by Django 3.1.7 on 2021-03-27 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_centers', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('emailId', models.EmailField(max_length=254)),
                ('serviceCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_centers.servicecenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.DecimalField(decimal_places=0, max_digits=6)),
                ('requestState', models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'rejected')])),
                ('problemDescriptionByCustomer', models.CharField(max_length=500)),
                ('problemDescriptionByMech', models.CharField(default=None, max_length=500)),
                ('mechanicArrived', models.BooleanField(default=False)),
                ('bill', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('requestedTime', models.DateTimeField()),
                ('requestAcceptanceTime', models.DateTimeField(default=None)),
                ('mechanicArrivalTime', models.DateTimeField(default=None)),
                ('serviceCompleteTime', models.DateTimeField(default=None)),
                ('locationState', models.CharField(max_length=500)),
                ('locationCity', models.CharField(max_length=500)),
                ('locationPinCode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('address', models.CharField(max_length=500)),
                ('assignedMechanic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mechanics.mechanic')),
                ('requestedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('requestedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_centers.servicecenter')),
            ],
        ),
        migrations.CreateModel(
            name='BillGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemResolved', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('associatedRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanics.bookingrequest')),
            ],
        ),
    ]
