# Generated by Django 3.1.7 on 2021-03-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='vehicleType',
            field=models.IntegerField(choices=[(0, 'two wheeler'), (1, 'three wheeler'), (2, 'four wheeler'), (3, 'heavy vehicle')], default=0),
            preserve_default=False,
        ),
    ]
